version: '3.4'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'phutran123'
      MYSQL_DATABASE: 'tutorial'
    volumes:
      - mysqldata:/var/lib/mysql
      # - ./tutorial.sql:/docker-entrypoint-initdb.d/tutorial.sql
    ports:
      - 3306:3306
volumes:
    mysqldata: {}